# Main repository BUILD file
# gazelle:prefix github.com/catalystcommunity/k8s-example-monorepo
load("@gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@rules_python//python:defs.bzl", "py_library")

gazelle_binary(
    name = "demo_gazelle_binary",
    languages = [
        "@gazelle//language/go",  # Built-in rule from gazelle for Golang.
        "@gazelle//language/proto",  # Built-in rule from gazelle for Protos.
        "@rules_python_gazelle_plugin//python",  # Use gazelle from rules_python.
    ],
    visibility = ["//visibility:public"],
)

gazelle(
    name = "gazelle",
    gazelle = ":demo_gazelle_binary",
)

py_library(
    name = "k8s-example-monorepo",
    srcs = ["web_client/node_modules/flatted/python/flatted.py"],
    visibility = ["//:__subpackages__"],
)
