module(
    name = "example_bzlmod",
    version = "0.0.0",
    compatibility_level = 1,
)
# Dependencies
bazel_dep(name = "rules_oci", version = "1.7.4")
# Including rules_pkg for pkg_tar which is needed to create tarballs for OCI images
bazel_dep(name = "rules_pkg", version = "1.0.1")

# OCI setup for containers
oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# Python alpine image for final container
oci.pull(
    name = "python_alpine_base",
    tag = "3.13-alpine",
    image = "docker.io/library/python",
    platforms = ["linux/amd64"],
)
use_repo(oci, "python_alpine_base")
