#!/usr/bin/env bash

# If you are used to a Makefile, this is where you do the work instead
set -e

THISSCRIPT=$(basename $0)

PROJECT_ROOT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# colors
GREEN=$'\e[0;32m'
NC=$'\e[0m'

# Modify for the help message
usage() {
    log_status "Usage"
    echo "${THISSCRIPT} command"
    echo ""
    echo "Commands:"
    echo ""
    echo "  setup       Set things up, obviously"
    echo "  updatedb    Get the DB up to latest. Make sure it is running and your env vars are set"
    echo ""
    exit 0
}

setup(){
    if ! command -v go 2>&1 >/dev/null
    then
        echo "Go is not installed, you'll have to do that first yourself"
        exit 1
    fi
    go install github.com/pressly/goose/v3/cmd/goose@latest
}

updatedb(){
    if ! command -v goose 2>&1 >/dev/null
    then
        echo "goose could not be found, running setup"
        setup
    fi

    cd "${PROJECT_ROOT_DIR}/coredb"
    goose up
    cd -
}

log_status() {
  echo "${GREEN}---------------------------------  ${1}  ---------------------------------${NC}"
}

# This should be last in the script, all other functions are named beforehand.
case "$1" in
    "setup")
        shift
        setup "$@"
        ;;
    "updatedb")
        shift
        updatedb "$@"
        ;;
    "runauth")
        shift
        runauth "$@"
        ;;
    *)
        usage
        ;;
esac

exit 0
