auth:
  enabled: true # enabled by default
  image:
    repository: quay.io/catalystcommunity/monodemo-auth
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion
    tag: ""
  prometheus:
    enabled: false
    path: /metrics
    port: 9000
    latencyHistogramsEnabled: true
  service:
    type: ClusterIP 
    port: 5080
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

app:
  enabled: true # enabled by default
  migrateJobName: "monodemo-migrate"
  image:
    repository: quay.io/catalystcommunity/monodemo-app
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion
    tag: ""
  prometheus:
    enabled: false
    path: /metrics
    port: 9000
    latencyHistogramsEnabled: true
  service:
    type: ClusterIP
    port: 6080
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  resources: {}

web:
  enabled: true # enabled by default
  image:
    repository: quay.io/catalystcommunity/monodemo-web
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion
    tag: ""
  service:
    type: ClusterIP
    port: 4080
  apiUrl: "http://auth-api-service:5080"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

migrations:
  jobName: "migrations"
  restartPolicy: "OnFailure"
  resources: {}
  # Useful if you have to run this a lot, like in a skaffold dev env
  setJobNameAsTimestamp: false
  ttlSecondsAfterFinished: 14400 # defaults to a day

grpc:
  maxMessageSizeBytes: "1000000000"

postgres:
  uri: postgresql://devuser:devpass@monodemo-postgresql:5432/monodemopg?sslmode=disable

storage:
  type: postgres

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# You could give a service account per service, but this is simpler for most use cases
# We did add _helpers entries to make this an easy exercise for the reader
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The base name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# The rest of these are also pretty standard, but are not implemented as separate template
# entries for simplicity reasons. These are for advanced security cases and for deployment
# styles you should avoid.
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


nodeSelector: {}

tolerations: []

affinity: {}

# Dependency charts
postgresql:
  auth:
    username: "devuser"
    postgresPassword: "devpass"
    password: "devpass"
    database: "monodemopg"
