apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.secretName" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
data:
  DB_URI: {{ .Values.postgres.uri | b64enc | quote }}
