apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.secretName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_URI: {{ .Values.postgres.uri | b64enc | quote }}
