load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "auth_tests",
    srcs = [
        "__init__.py",
        "datautils.py",
    ],
    imports = [".."],
    visibility = ["//auth_api:__subpackages__"],
    deps = [
        "//auth_api/auth/core:auth_core",
        "@pip//sqlalchemy",
    ],
)

py_test(
    name = "session_views_test",
    srcs = ["session_views_test.py"],
    imports = [".."],
    deps = [
        ":auth_tests",
        ":test_utils",
        "//auth_api/auth/core:auth_core",
        "//auth_api/auth/views:auth_views",
        "@pip//fastapi",
    ],
)

py_test(
    name = "setup_test",
    srcs = ["setup_test.py"],
    imports = [".."],
    deps = [
        "//auth_api/auth/core:auth_core",
        "@pip//pytest",
        "@pip//sqlalchemy",
        "@pip//transaction",
    ],
)

py_test(
    name = "test_client",
    srcs = ["test_client.py"],
    imports = [".."],
    deps = [
        "//auth_api/auth:auth_auth",
        "@pip//fastapi",
    ],
)

py_test(
    name = "test_utils",
    srcs = ["test_utils.py"],
    imports = [".."],
)

py_test(
    name = "user_views_test",
    srcs = ["user_views_test.py"],
    imports = [".."],
    deps = [
        ":auth_tests",
        ":test_utils",
        "//auth_api/auth/core:auth_core",
        "//auth_api/auth/views:auth_views",
        "@pip//fastapi",
    ],
)

py_test(
    name = "verification_test",
    srcs = ["verification_test.py"],
    imports = [".."],
    deps = [
        ":auth_tests",
        ":test_utils",
        "//auth_api/auth:auth_auth",
        "//auth_api/auth/core:auth_core",
        "@pip//fastapi",
        "@pip//sqlalchemy",
    ],
)
